#!/usr/bin/env bash

# Allows the script to stop running when a command fails (-e).
# Additionally treats unset variables as an error (-u) and
# fails pipelines when any command within them fails (-o pipefail)
set -euo pipefail

# Helper function for error handling
die() {
	echo "Error: $*" >&2;
	exit 1;
}

# Store the help menu in "$usage"
read usage <<EOF
Usage: $(basename "$0") <project-name> [OPTS]...
-------------------------------------------------
Where OPTS includes:
-b => Creates a minimal, flattened project structure.
-f => Creates a full project structure (same as specifying -gsm)
-g => Creates a Git repository for the project.
-h => Show this message and exit.
-m => Initialises a Makefile for the project.
-s => Initialises Bash build scripts for the project.
-v => Enable verbose output
-x => Uses fixed format source code instead of free format.
EOF
