#!/usr/bin/env bash

# Allows the script to stop running when a command fails (-e).
# Additionally treats unset variables as an error (-u) and
# fails pipelines when any command within them fails (-o pipefail)
set -euo pipefail

# Helper function for error handling
die() {
	# Display an error message to stderr
	echo "Error: $*" >&2
	# Exit the script with an error code
	exit 1
}

# Store the help menu in "$usage"
read -r usage <<EOF
Usage: $(basename "$0") <project-name> [OPTS]...
-------------------------------------------------
Where OPTS includes:
-b => Creates a minimal, flattened project structure.
-f => Creates a full project structure (same as specifying -gsm)
-g => Creates a Git repository for the project.
-h => Show this message and exit.
-m => Initialises a Makefile for the project.
-s => Initialises Bash build scripts for the project.
-v => Enable verbose output
-x => Uses fixed format source code instead of free format.
EOF

# Initialise Boolean flags for the above options
bare=false # Bare, flat project structure (no src or bin folders)
fixed=false # Fixed format code
gitRepo=false # Git repository
makefile=false # Makefile
scripts=false # Bash build scripts
verbose=false # Verbose output

# String variables
projName="" # Name of project directory

# Function for verbose output
vout() {
	if [[ "$verbose" == true ]]; then
		# Output a message if verbose output is on
		echo "[VRB] $*"
	fi
}

if [[ -z "$1" ]]; then
	die "Project name not specified."
fi

# Store the project name in a variable
projName="$1"

# Remove the project name from the arguments list
shift

while getopts 'bfghmsvx' opt; do
	case "$opt" in
		b)
			# Ensure a bare project is created and not a full project
			bare=true

			# Set all build-related flags to false
			makefile=false
			scripts=false
			gitRepo=false
			;;
		f)
			# Ensure that a bare project is not created
			bare=false

			# Set all build-related flags to true
			makefile=true
			scripts=true
			gitRepo=true
			;;
		g)
			# Allows for creating a Git repo later on in the script
			gitRepo=true
			;;
		h)
			# Display the help message and exit
			echo "$usage"
			exit 0
			;;
		m)
			makefile=true
			;;
		s)
			scripts=true
			;;
		v)
			verbose=true
			;;
		x)
			fixed=true
			;;
		?)
			die "Invalid flag: $opt"
			;;
	esac
done

mkdir "$projName" || die "Project directory failed to be created."

# Create the empty, flattened project and exit
if [[ "$bare" == true ]]; then
	# run commands in a subshell
	(
		# Change into project directory
		cd "$projName"
		vout "In directory $projName"

		if [[ "$fixed" == true ]]; then
			# Create an empty fixed format COBOL file
			touch main.cbl
			vout "Created empty fixed format COBOL file"
		else
			# Create an empty free format COBOL file
			touch main.cob
			vout "Created empty free format COBOL file"
		fi

		# Create an empty README file
		touch README.md
		vout "Created empty README"

		if [[ "$gitRepo" == true ]]; then
			# Create an empty .gitignore
			touch .gitignore
			vout "Created empty .gitignore"
		fi

		if [[ "$makefile" == true ]]; then
			# Create an empty Makefile
			touch makefile
			vout "Created empty Makefile"
		fi

		if [[ "$scripts" == true  ]]; then
			touch build.sh
			vout "Created empty build Bash script"
		fi
	)

	# Stop the script
	exit 0
fi
